%% SDPE MATLAB initialization script
% Project: PGS SINV RC MATLAB/Simulink SIL
% Generated by tools/SDPE_v2. Do not edit generated variables directly.

% Notes:
%   Windows SIL platform, plant and sensing settings for all SINV commissioning models.

%% Project metadata
PGS_SINV_RC_SIM_SDPE_PROJECT_ID = 'pgs_sinv_rc_simulate';

PGS_SINV_RC_SIM_SDPE_PROJECT_SUITE = 'pgs_sinv_rc';

PGS_SINV_RC_SIM_SDPE_PROJECT_VERSION = '1.0.0';

PGS_SINV_RC_SIM_SDPE_PROJECT_UPDATED_AT = '2026-07-22';

%% SIL Runtime
% Automatically request CiA402 ENABLE_OPERATION in the simulation executable.
SINV_SIM_AUTO_ENABLE = true;

% SPECIFY_ENABLE_ADC_CALIBRATE is disabled in the SDPE project requirement.
% SPECIFY_ENABLE_ADC_CALIBRATE = true;

% ENABLE_GMP_DL_PIL_SIM is disabled in the SDPE project requirement.
% ENABLE_GMP_DL_PIL_SIM = true;

%% Commissioning
% 1 open-loop R load; 2 current-loop R load with an explicit project application mode; 3 grid current loop; 4 grid power loop; 5 DC-bus rectifier loop.
% Options: (1), (2), (3), (4), (5)
BUILD_LEVEL = 2;

%% Application Mode
% BUILD_LEVEL 2 application selector: 0 standard fixed-current BL2; 1 2023A standalone RL-terminal voltage loop.
% Options: (0), (1)
SINV_APP_MODE = 1;

% Enable the existing single-phase H-bridge dead-time compensation for the 2023A standalone inverter mode.
% Options: (0), (1)
SINV_2023A_ENABLE_DEADTIME_COMP = 1;

% Enable measured load-current feedforward in the 2023A standalone voltage loop.
% Options: (0), (1)
SINV_2023A_ENABLE_LOAD_CURRENT_FF = 1;

% Enable analytical filter-capacitor current feedforward in the 2023A standalone voltage loop.
% Options: (0), (1)
SINV_2023A_ENABLE_CAP_CURRENT_FF = 1;

%% Requirement bindings
% Application-mode constant selecting the unchanged standard BUILD_LEVEL 2 fixed-current reference.
SINV_APP_MODE_STANDARD_BL2 = 0;

% Application-mode constant selecting the 2023A standalone RL-terminal voltage loop inside BUILD_LEVEL 2.
SINV_APP_MODE_2023A_SINGLE = 1;

% 2023A standalone-mode physical RL-terminal RMS voltage command.
SINV_2023A_UO_REF_RMS_V = 24.0;

% 2023A standalone-mode internal phase-accumulator frequency; the PLL does not set this frequency.
SINV_2023A_OUTPUT_FREQ_HZ = 50.0;

% Time for the standalone voltage-reference peak to ramp linearly from zero to its rated value.
SINV_2023A_SOFTSTART_TIME_S = 0.50;

% Conservative PU voltage-error to PU peak-current proportional gain; with the 12 Ohm load its low-frequency proportional loop gain is approximately 0.25, leaving the 50 Hz QPR term to remove fundamental error.
SINV_2023A_VOLTAGE_LOOP_KP = 0.05;

% Fundamental quasi-resonant gain; with the measured 12 Ohm load it gives approximately 175 PU loop gain at 50 Hz before current-loop dynamics.
SINV_2023A_VOLTAGE_LOOP_KR = 35.0;

% Narrow QPR resonant half-bandwidth around the fixed 50 Hz standalone reference.
SINV_2023A_VOLTAGE_LOOP_WI_HZ = 0.20;

% Absolute peak IL-reference safety limit in PU; 0.28 PU is 3.96 A peak while the rated case requires approximately 2.84 A peak.
SINV_2023A_CURRENT_REF_LIMIT_PEAK_PU = 0.28;

% Symmetric QPR output clamp in PU peak current; the effective limit is the smaller of this value and the current-reference safety limit.
SINV_2023A_VOLTAGE_LOOP_OUTPUT_LIMIT_PU = 0.28;

% Gain applied to measured load-current peak PU before adding it to the 2023A inductor-current reference.
SINV_2023A_LOAD_CURRENT_FF_GAIN = 1.02;

% Gain applied to the analytical capacitor-current feedforward term in the 2023A inductor-current reference.
SINV_2023A_CAP_CURRENT_FF_GAIN = 1.0;

% SIL controller and PWM update frequency.
CONTROLLER_FREQUENCY = 20e3;

% Plant switching frequency.
SINV_PWM_FREQUENCY_HZ = 20e3;

% Virtual PWM compare maximum.
CTRL_PWM_CMP_MAX = 2999;

% Virtual PWM deadband counts.
CTRL_PWM_DEADBAND_CMP = 50;

% ADC resolution used by all sensor blocks.
CTRL_ADC_RESOLUTION = 12;

% ADC reference voltage.
CTRL_ADC_VOLTAGE_REF = 3.3;

% Rated and nominal DC-bus voltage.
CTRL_DCBUS_VOLTAGE = 60.0;

% Nominal grid/load RMS voltage.
CTRL_GRID_VOLTAGE_RMS = 24.0;

% Rated RMS AC current.
CTRL_RATED_CURRENT_RMS = 10.0;

% Peak voltage PU base.
CTRL_VOLTAGE_BASE = 34.0;

% Peak current PU base.
CTRL_CURRENT_BASE = 14.14;

% AC filter series inductance.
CTRL_AC_INDUCTANCE = 480e-6;

% AC filter series resistance.
CTRL_AC_RESISTANCE = 0.10;

% AC filter shunt capacitance.
SINV_FILTER_CAPACITANCE_F = 22e-6;

% Filter capacitor ESR.
SINV_FILTER_CAP_ESR_OHM = 0.10;

% DC-link capacitance.
SINV_DC_CAPACITANCE_F = 2200e-6;

% Resistive load for levels 1 and 2.
SINV_RLOAD_OHM = 12.0;

% DC-side load for level 5. At 60 V this draws 120 W, within the configured converter current rating.
SINV_RECTIFIER_RLOAD_OHM = 30.0;

% AC voltage sensor sensitivity in V/V.
CTRL_AC_VOLTAGE_SENSITIVITY = 0.020;

% AC voltage ADC bias.
CTRL_AC_VOLTAGE_BIAS = 1.65;

% AC current sensor sensitivity in V/A.
CTRL_AC_CURRENT_SENSITIVITY = 0.150;

% AC current ADC bias.
CTRL_AC_CURRENT_BIAS = 1.65;

% DC bus voltage sensor sensitivity in V/V.
CTRL_DC_VOLTAGE_SENSITIVITY = 0.040;

% DC bus voltage ADC bias.
CTRL_DC_VOLTAGE_BIAS = 0.0;

% DC bus overvoltage threshold.
CTRL_PROT_VBUS_MAX = 90.0;

% Fast AC peak-current threshold.
CTRL_PROT_IAC_PEAK_MAX = 18.0;

% Controller divergence threshold; BUILD_LEVEL 5 masks it only during passive-rectifier takeover.
CTRL_PROT_VCTRL_MAX_PU = 1.5;

% Minimum precharged DC bus accepted by startup.
CTRL_DCBUS_READY_MIN = 25.0;

% Maximum DC bus accepted by startup.
CTRL_DCBUS_READY_MAX = 90.0;

% ADC calibration timeout.
TIMEOUT_ADC_CALIB_MS = 3000;

% Plant MOSFET on resistance.
SINV_MODEL_MOSFET_RON = 4.6e-3;

% Body-diode on resistance.
SINV_MODEL_DIODE_RON = 0.01;

% Body-diode forward voltage.
SINV_MODEL_DIODE_VF = 0.5;

%% Local helpers
function value = sdpe_select(condition, true_value, false_value)
if condition
    value = true_value;
else
    value = false_value;
end
end
