#ifndef FSBB_BUILD4_CONTROLLER_H_
#define FSBB_BUILD4_CONTROLLER_H_

#include "fsbb_inner_current_loop.h"

/**
 * @brief Runtime operating mode of Build Level 4.
 */
typedef enum _tag_fsbb_build4_mode_e
{
    FSBB_BUILD4_MODE_TEST = 0,
    FSBB_BUILD4_MODE_CV,
    FSBB_BUILD4_MODE_CC
} fsbb_build4_mode_e;

/**
 * @brief Build Level 4 controller state.
 */
typedef struct _tag_fsbb_build4_controller_t
{
    /* Candidate references generated by outer loops */
    ctrl_gt i_L_ref_cv;
    ctrl_gt i_L_ref_cc;

    /* Final selected inductor-current reference */
    ctrl_gt i_L_ref_cmd;

    /* Allowed inductor-current reference range */
    ctrl_gt i_L_ref_max;
    ctrl_gt i_L_ref_min;

    /* Current CV/CC operating mode */
    fsbb_build4_mode_e mode;

} fsbb_build4_controller_t;

/**
 * @brief Initialize Build Level 4 controller state.
 */
GMP_STATIC_INLINE void ctl_init_fsbb_build4_controller(fsbb_build4_controller_t* obj, ctrl_gt i_L_ref_max,
                                                       ctrl_gt i_L_ref_min)
{
    obj->i_L_ref_cv = float2ctrl(0.0f);
    obj->i_L_ref_cc = float2ctrl(0.0f);
    obj->i_L_ref_cmd = float2ctrl(0.0f);

    obj->i_L_ref_max = i_L_ref_max;
    obj->i_L_ref_min = i_L_ref_min;

    obj->mode = FSBB_BUILD4_MODE_TEST;
}

/**
 * @brief Clear Build Level 4 runtime states.
 */
GMP_STATIC_INLINE void ctl_clear_fsbb_build4_controller(fsbb_build4_controller_t* obj)
{
    obj->i_L_ref_cv = float2ctrl(0.0f);
    obj->i_L_ref_cc = float2ctrl(0.0f);
    obj->i_L_ref_cmd = float2ctrl(0.0f);

    obj->mode = FSBB_BUILD4_MODE_TEST;
}

/**
 * @brief Execute one Build Level 4 control step.
 *
 * At the current development stage, i_L_ref_input is a temporary
 * externally supplied current reference. Later it will be replaced
 * by the CV/CC selector output.
 */
GMP_STATIC_INLINE ctrl_gt ctl_step_fsbb_build4(fsbb_build4_controller_t* obj, ctl_dcdc_core_t* core,
                                               ctrl_gt i_L_ref_input)
{
    /*
     * ADC data must be ingested and filtered exactly once
     * during each controller cycle.
     */
    ctl_dcdc_internal_ingest_and_filter(core);

    /*
     * Store and limit the final inductor-current reference.
     */
    obj->i_L_ref_cmd = ctl_sat(i_L_ref_input, obj->i_L_ref_max, obj->i_L_ref_min);

    /*
     * Execute the already validated inductor-current inner loop.
     */
    return ctl_step_fsbb_inductor_current_loop(core, obj->i_L_ref_cmd, obj->i_L_ref_max, obj->i_L_ref_min);
}

#endif // FSBB_BUILD4_CONTROLLER_H_
