#ifndef FSBB_BUILD4_CONTROLLER_H_
#define FSBB_BUILD4_CONTROLLER_H_

#include "fsbb_inner_current_loop.h"

/**
 * @brief Runtime operating mode of Build Level 4.
 */
typedef enum _tag_fsbb_build4_mode_e
{
    FSBB_BUILD4_MODE_TEST = 0,
    FSBB_BUILD4_MODE_CV,
    FSBB_BUILD4_MODE_CC
} fsbb_build4_mode_e;

/**
 * @brief Build Level 4 controller state.
 */
typedef struct _tag_fsbb_build4_controller_t
{
    /* Candidate references generated by outer loops */
    ctrl_gt i_L_ref_cv;
    ctrl_gt i_L_ref_cc;

    /* Final selected inductor-current reference */
    ctrl_gt i_L_ref_cmd;

    /* Allowed inductor-current reference range */
    ctrl_gt i_L_ref_max;
    ctrl_gt i_L_ref_min;
    /* CV/CC mode-switching hysteresis */
    ctrl_gt switch_hysteresis;

    /* Current CV/CC operating mode */
    fsbb_build4_mode_e mode;

} fsbb_build4_controller_t;

/**
 * @brief Initialize Build Level 4 controller state.
 */
GMP_STATIC_INLINE void ctl_init_fsbb_build4_controller(fsbb_build4_controller_t* obj, ctrl_gt i_L_ref_max,
                                                       ctrl_gt i_L_ref_min)
{
    obj->i_L_ref_cv = float2ctrl(0.0f);
    obj->i_L_ref_cc = float2ctrl(0.0f);
    obj->i_L_ref_cmd = float2ctrl(0.0f);

    obj->i_L_ref_max = i_L_ref_max;
    obj->i_L_ref_min = i_L_ref_min;
    obj->switch_hysteresis = switch_hysteresis;

    obj->mode = FSBB_BUILD4_MODE_TEST;
}

/**
 * @brief Clear Build Level 4 runtime states.
 */
GMP_STATIC_INLINE void ctl_clear_fsbb_build4_controller(fsbb_build4_controller_t* obj)
{
    obj->i_L_ref_cv = float2ctrl(0.0f);
    obj->i_L_ref_cc = float2ctrl(0.0f);
    obj->i_L_ref_cmd = float2ctrl(0.0f);

    obj->mode = FSBB_BUILD4_MODE_TEST;
}
/**
 * @brief Select the final inductor-current reference from
 *        the CV and CC candidate references.
 *
 * @param[in,out] obj Build Level 4 controller object.
 * @param[in] i_L_ref_cv_input Candidate current reference from voltage loop.
 * @param[in] i_L_ref_cc_input Candidate current reference from current-limit loop.
 *
 * @return Final selected inductor-current reference.
 */
GMP_STATIC_INLINE ctrl_gt ctl_step_fsbb_cvcc_selector(fsbb_build4_controller_t* obj, ctrl_gt i_L_ref_cv_input,
                                                      ctrl_gt i_L_ref_cc_input)
{
    /*
     * Limit both candidate references before comparing them.
     */
    obj->i_L_ref_cv = ctl_sat(i_L_ref_cv_input, obj->i_L_ref_max, obj->i_L_ref_min);

    obj->i_L_ref_cc = ctl_sat(i_L_ref_cc_input, obj->i_L_ref_max, obj->i_L_ref_min);

    /*
    * Initialize the mode according to the smaller candidate.
    */
    if (obj->mode == FSBB_BUILD4_MODE_TEST)
    {
        if (obj->i_L_ref_cv <= obj->i_L_ref_cc)
        {
            obj->mode = FSBB_BUILD4_MODE_CV;
        }
        else
        {
            obj->mode = FSBB_BUILD4_MODE_CC;
        }
    }
    /*
    * While operating in CV mode, switch to CC only when the
    * CC candidate is lower by more than the hysteresis band.
    */
    else if (obj->mode == FSBB_BUILD4_MODE_CV)
    {
        if ((obj->i_L_ref_cc + obj->switch_hysteresis) < obj->i_L_ref_cv)
        {
            obj->mode = FSBB_BUILD4_MODE_CC;
        }
    }
    /*
    * While operating in CC mode, switch back to CV only when
    * the CV candidate is lower by more than the hysteresis band.
    */
    else
    {
        if ((obj->i_L_ref_cv + obj->switch_hysteresis) < obj->i_L_ref_cc)
        {
            obj->mode = FSBB_BUILD4_MODE_CV;
        }
    }

    /*
    * Select the reference corresponding to the retained mode.
    */
    if (obj->mode == FSBB_BUILD4_MODE_CC)
    {
        obj->i_L_ref_cmd = obj->i_L_ref_cc;
    }
    else
    {
        obj->i_L_ref_cmd = obj->i_L_ref_cv;
    }

    return obj->i_L_ref_cmd;
}

/**
 * @brief Execute one Build Level 4 control step.
 *
 * At the current development stage, the CV and CC candidate
 * references are supplied externally for integration testing.
 * Later they will be generated by the two outer loops.
 */
GMP_STATIC_INLINE ctrl_gt ctl_step_fsbb_build4(fsbb_build4_controller_t* obj, ctl_dcdc_core_t* core,
                                               ctrl_gt i_L_ref_cv_input, ctrl_gt i_L_ref_cc_input)
{
    /*
     * Update ADC feedback and filters exactly once
     * during each controller cycle.
     */
    ctl_dcdc_internal_ingest_and_filter(core);

    /*
     * Select the final inductor-current reference.
     */
    ctl_step_fsbb_cvcc_selector(obj, i_L_ref_cv_input, i_L_ref_cc_input);

    /*
     * Execute the inductor-current inner loop.
     */
    return ctl_step_fsbb_inductor_current_loop(core, obj->i_L_ref_cmd, obj->i_L_ref_max, obj->i_L_ref_min);
}

#endif // FSBB_BUILD4_CONTROLLER_H_
