#ifndef FSBB_BUILD4_CONTROLLER_H_
#define FSBB_BUILD4_CONTROLLER_H_

#include "fsbb_inner_current_loop.h"

/**
 * @brief Runtime operating mode of Build Level 4.
 */
typedef enum _tag_fsbb_build4_mode_e
{
    FSBB_BUILD4_MODE_TEST = 0,
    FSBB_BUILD4_MODE_CV,
    FSBB_BUILD4_MODE_CC
} fsbb_build4_mode_e;

/**
 * @brief Build Level 4 controller state.
 */
typedef struct _tag_fsbb_build4_controller_t
{
    /* Independent output-current outer-loop PI */
    ctl_pid_t output_current_pid;

    /* Candidate references generated by outer loops */
    ctrl_gt i_L_ref_cv;
    ctrl_gt i_L_ref_cc;

    /* Final selected inductor-current reference */
    ctrl_gt i_L_ref_cmd;

    /* Allowed inductor-current reference range */
    ctrl_gt i_L_ref_max;
    ctrl_gt i_L_ref_min;
    /* CV/CC mode-switching hysteresis */
    ctrl_gt switch_hysteresis;

    /* Current CV/CC operating mode */
    fsbb_build4_mode_e mode;

} fsbb_build4_controller_t;

/**
 * @brief Initialize Build Level 4 controller state.
 */
GMP_STATIC_INLINE void ctl_init_fsbb_build4_controller(fsbb_build4_controller_t* obj, ctrl_gt i_L_ref_max,
                                                       ctrl_gt i_L_ref_min, ctrl_gt switch_hysteresis,
                                                       parameter_gt output_current_kp,
                                                       parameter_gt output_current_ti, parameter_gt fs)
{
    ctl_init_pid_Tmode(&obj->output_current_pid, output_current_kp, output_current_ti, 0.0f, fs);
    ctl_set_pid_limit(&obj->output_current_pid, i_L_ref_max, i_L_ref_min);
    ctl_set_pid_int_limit(&obj->output_current_pid, i_L_ref_max, i_L_ref_min);

    obj->i_L_ref_cv = float2ctrl(0.0f);
    obj->i_L_ref_cc = float2ctrl(0.0f);
    obj->i_L_ref_cmd = float2ctrl(0.0f);

    obj->i_L_ref_max = i_L_ref_max;
    obj->i_L_ref_min = i_L_ref_min;
    obj->switch_hysteresis = switch_hysteresis;

    obj->mode = FSBB_BUILD4_MODE_TEST;
}

/**
 * @brief Clear Build Level 4 runtime states.
 */
GMP_STATIC_INLINE void ctl_clear_fsbb_build4_controller(fsbb_build4_controller_t* obj)
{
    ctl_clear_pid(&obj->output_current_pid);

    obj->i_L_ref_cv = float2ctrl(0.0f);
    obj->i_L_ref_cc = float2ctrl(0.0f);
    obj->i_L_ref_cmd = float2ctrl(0.0f);

    obj->mode = FSBB_BUILD4_MODE_TEST;
}

/**
 * @brief Select the final inductor-current reference from
 *        the CV and CC candidate references.
 *
 * @param[in,out] obj Build Level 4 controller object.
 * @param[in] i_L_ref_cv_input Candidate current reference from voltage loop.
 * @param[in] i_L_ref_cc_input Candidate current reference from current-limit loop.
 *
 * @return Final selected inductor-current reference.
 */
GMP_STATIC_INLINE ctrl_gt ctl_step_fsbb_cvcc_selector(fsbb_build4_controller_t* obj, ctrl_gt i_L_ref_cv_input,
                                                      ctrl_gt i_L_ref_cc_input)
{
    /*
     * Limit both candidate references before comparing them.
     */
    obj->i_L_ref_cv = ctl_sat(i_L_ref_cv_input, obj->i_L_ref_max, obj->i_L_ref_min);

    obj->i_L_ref_cc = ctl_sat(i_L_ref_cc_input, obj->i_L_ref_max, obj->i_L_ref_min);

    /*
    * Initialize the mode according to the smaller candidate.
    */
    if (obj->mode == FSBB_BUILD4_MODE_TEST)
    {
        if (obj->i_L_ref_cv <= obj->i_L_ref_cc)
        {
            obj->mode = FSBB_BUILD4_MODE_CV;
        }
        else
        {
            obj->mode = FSBB_BUILD4_MODE_CC;
        }
    }
    /*
    * While operating in CV mode, switch to CC only when the
    * CC candidate is lower by more than the hysteresis band.
    */
    else if (obj->mode == FSBB_BUILD4_MODE_CV)
    {
        if ((obj->i_L_ref_cc + obj->switch_hysteresis) < obj->i_L_ref_cv)
        {
            obj->mode = FSBB_BUILD4_MODE_CC;
        }
    }
    /*
    * While operating in CC mode, switch back to CV only when
    * the CV candidate is lower by more than the hysteresis band.
    */
    else
    {
        if ((obj->i_L_ref_cv + obj->switch_hysteresis) < obj->i_L_ref_cc)
        {
            obj->mode = FSBB_BUILD4_MODE_CV;
        }
    }

    /*
    * Always apply the more restrictive candidate reference.
    *
    * The operating mode uses hysteresis to prevent state chatter,
    * while the control command always satisfies both CV and CC
    * candidate constraints.
    */
    if (obj->i_L_ref_cv <= obj->i_L_ref_cc)
    {
        obj->i_L_ref_cmd = obj->i_L_ref_cv;
    }
    else
    {
        obj->i_L_ref_cmd = obj->i_L_ref_cc;
    }
    return obj->i_L_ref_cmd;
}
GMP_STATIC_INLINE ctrl_gt ctl_finish_fsbb_build4_step(fsbb_build4_controller_t* obj, ctl_dcdc_core_t* core,
                                                      ctrl_gt i_L_ref_cv, ctrl_gt i_L_ref_cc)
{
    ctl_step_fsbb_cvcc_selector(obj, i_L_ref_cv, i_L_ref_cc);
    core->is_current_dominant = (obj->mode == FSBB_BUILD4_MODE_CC) ? 1 : 0;

    return ctl_step_fsbb_inductor_current_loop(core, obj->i_L_ref_cmd, obj->i_L_ref_max, obj->i_L_ref_min);
}

/** Execute one Build Level 4 step using externally supplied self-test candidates. */
GMP_STATIC_INLINE ctrl_gt ctl_step_fsbb_build4_self_test(fsbb_build4_controller_t* obj, ctl_dcdc_core_t* core,
                                                         ctrl_gt i_L_ref_cv, ctrl_gt i_L_ref_cc)
{
    ctl_dcdc_internal_ingest_and_filter(core);
    return ctl_finish_fsbb_build4_step(obj, core, i_L_ref_cv, i_L_ref_cc);
}

/** Execute the voltage/current outer loops and the verified inductor-current inner loop. */
GMP_STATIC_INLINE ctrl_gt ctl_step_fsbb_build4(fsbb_build4_controller_t* obj, ctl_dcdc_core_t* core,
                                               ctrl_gt voltage_target, ctrl_gt output_current_limit)
{
    ctrl_gt i_L_ref_cv;
    ctrl_gt i_L_ref_cc;

    ctl_dcdc_internal_ingest_and_filter(core);

    core->v_ramp_ref = ctl_step_slope_limiter(&core->ramp_v, voltage_target);
    i_L_ref_cv = ctl_step_pid_ser(&core->voltage_pid, core->v_ramp_ref - core->filter_v_out.out);
    i_L_ref_cc =
        ctl_step_pid_ser(&obj->output_current_pid, output_current_limit - core->filter_i_load.out);

    ctl_step_fsbb_cvcc_selector(obj, i_L_ref_cv, i_L_ref_cc);

    /* Track the applied minimum reference in the non-limiting outer loop. */
    if (obj->i_L_ref_cv > obj->i_L_ref_cmd)
        ctl_pid_clamping_correction_using_real_output(&core->voltage_pid, obj->i_L_ref_cmd);
    if (obj->i_L_ref_cc > obj->i_L_ref_cmd)
        ctl_pid_clamping_correction_using_real_output(&obj->output_current_pid, obj->i_L_ref_cmd);

    core->is_current_dominant = (obj->mode == FSBB_BUILD4_MODE_CC) ? 1 : 0;
    return ctl_step_fsbb_inductor_current_loop(core, obj->i_L_ref_cmd, obj->i_L_ref_max, obj->i_L_ref_min);
}

#endif // FSBB_BUILD4_CONTROLLER_H_
